### ISSUE TITLE
Blank first reference in rendered pdf

### ISSUE THREAD

**Issue by notesofdabbler** [quarto-journals/acs#1]
I had posted the issue of blank first reference in rendered pdf and after that found a solution to the issue. I had posted both in RStudio community site at this [location](https://community.rstudio.com/t/quarto-acs-journal-template-produces-a-blank-first-reference/156147). I am posting the link to it as an issue here in case it the right achemso.bst file can be used in this repository to avoid the problem for future users.

**Comment by dragonstyle** [comment]
Thanks for sharing this - I've updated the extension itself to use the correct BST file as you diagnosed!

**Comment by notesofdabbler** [comment]
Thanks for quickly fixing this.
